-- For table REGION
ALTER TABLE REGION
ADD PRIMARY KEY (R_REGIONKEY);

-- For table NATION
ALTER TABLE NATION
ADD PRIMARY KEY (N_NATIONKEY);

ALTER TABLE NATION
ADD CONSTRAINT N_FK_REGION FOREIGN KEY (N_REGIONKEY) REFERENCES REGION (R_REGIONKEY);

-- For table PART
ALTER TABLE PART
ADD PRIMARY KEY (P_PARTKEY);

-- For table SUPPLIER
ALTER TABLE SUPPLIER
ADD PRIMARY KEY (S_SUPPKEY);

ALTER TABLE SUPPLIER
ADD CONSTRAINT S_FK_NATION FOREIGN KEY (S_NATIONKEY) REFERENCES NATION;

-- For table PARTSUPP
ALTER TABLE PARTSUPP
ADD PRIMARY KEY (PS_PARTKEY,PS_SUPPKEY);

-- For table CUSTOMER
ALTER TABLE CUSTOMER
ADD PRIMARY KEY (C_CUSTKEY);

ALTER TABLE CUSTOMER
ADD CONSTRAINT C_FK_NATION FOREIGN KEY (C_NATIONKEY) REFERENCES NATION;

-- For table LINEITEM
ALTER TABLE LINEITEM
ADD PRIMARY KEY (L_ORDERKEY,L_LINENUMBER);

-- For table ORDERS
ALTER TABLE ORDERS
ADD PRIMARY KEY (O_ORDERKEY);

-- For table PARTSUPP
ALTER TABLE PARTSUPP
ADD CONSTRAINT PS_FK_SUPPLIER FOREIGN KEY (PS_SUPPKEY) REFERENCES SUPPLIER;

ALTER TABLE PARTSUPP
ADD CONSTRAINT PS_FK_PART FOREIGN KEY (PS_PARTKEY) REFERENCES PART;

-- For table ORDERS
ALTER TABLE ORDERS
ADD CONSTRAINT O_FK_CUSTOMER FOREIGN KEY (O_CUSTKEY) REFERENCES CUSTOMER;


-- For table LINEITEM
ALTER TABLE LINEITEM
ADD CONSTRAINT L_FK_ORDER FOREIGN KEY (L_ORDERKEY)  REFERENCES ORDERS;

ALTER TABLE LINEITEM
ADD CONSTRAINT L_FK_PARTSUPP FOREIGN KEY  (L_PARTKEY,L_SUPPKEY) 
REFERENCES PARTSUPP;



